### ISSUE TITLE
Cannot install on node 10.0.0

### ISSUE THREAD

**Issue by linusnorton** [marcominetti/node-memwatch#39]
```../src/init.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/init.cc:20:9: error: ‘AddGCEpilogueCallback’ is not a member of ‘v8::V8’
         v8::V8::AddGCEpilogueCallback(memwatch::after_gc);
         ^
memwatch.target.mk:98: recipe for target 'Release/obj.target/memwatch/src/init.o' failed
make: *** [Release/obj.target/memwatch/src/init.o] Error 1
make: Leaving directory './node_modules/memwatch-next/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.13.16-041316-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

Doesn't seem to like v8 version 6.6

**Comment by AlexVyi** [comment]
/Users/alexandrupetru/.node-gyp/10.1.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
../src/memwatch.cc:129:35: error: expected ';' after expression
                Nan::AsyncResource async("nan:Callback:Call");
                                  ^
                                  ;
../src/memwatch.cc:129:22: error: no member named 'AsyncResource' in namespace 'Nan'
                Nan::AsyncResource async("nan:Callback:Call");
                ~~~~~^
../src/memwatch.cc:129:36: error: use of undeclared identifier 'async'
                Nan::AsyncResource async("nan:Callback:Call");
                                   ^
../src/memwatch.cc:130:38: error: use of undeclared identifier 'async'
                g_cb->Call(3, argv, &async);
                                     ^
../src/memwatch.cc:206:31: error: expected ';' after expression
            Nan::AsyncResource async("nan:Callback:Call");
                              ^
                              ;
../src/memwatch.cc:206:18: error: no member named 'AsyncResource' in namespace 'Nan'
            Nan::AsyncResource async("nan:Callback:Call");
            ~~~~~^
../src/memwatch.cc:206:32: error: use of undeclared identifier 'async'
            Nan::AsyncResource async("nan:Callback:Call");
                               ^
../src/memwatch.cc:207:34: error: use of undeclared identifier 'async'
            g_cb->Call(3, argv, &async);
                                 ^
4 warnings and 8 errors generated.
make: *** [Release/obj.target/memwatch/src/memwatch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alexandrupetru/WebstormProjects/epkstore/node_modules/node-memwatch
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-memwatch@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-memwatch@1.0.1 install script.

**Comment by AlexVyi** [comment]
It works with Node 10 on Ubuntu 16.04 but it fails on High Sierra.Sorry for not being specific.

**Comment by stsvilik** [comment]
@eduardbcom Why not just create a PR to the original repo? Isn't that what open source is about?

**Comment by schmod** [comment]
I think the issue is that it's gonna take some more work to make a version that works on both versions.

**Comment by adymorz** [comment]
I have got the same error message on Windows 10 1903 with node v10.16.0:

```
  win_delay_load_hook.cc
c:\...\project_name\node_modules\memwatch-next\src\init.cc(20): error C2039: "AddGCEpilogueCallback": Ist kein Element von "v8::V8" [c:\...\project_name\node_modules\memwatch-next\bu
ild\memwatch.vcxproj]
  c:\users\adrian dymorz\appdata\local\node-gyp\cache\10.16.0\include\node\v8.h(8087): note: Siehe Deklaration von "v8::V8"
c:\...\project_name\node_modules\memwatch-next\src\init.cc(20): error C3861: "AddGCEpilogueCallback": Bezeichner wurde nicht gefunden. [c:\...\project_name\node_modules\memwatch-next
\build\memwatch.vcxproj]
```

Unfortunataly I have no idea (yet) how to avoid it.
